### ISSUE TITLE
stops anything currently playing

### ISSUE THREAD

**Issue by smartaleciam** [whitesoup12/remote-falcon-tracker#29]
i have enabled the remote-falcon on the fpp , an if i try to play anything it stops it gracefully, it wont repeat or even play my play lists due to it "gracefully stopping"
is there a setting in my remotefalcon.com site that is making this happen? 
or is there something else?

Currently ive had to turn off remote falcon on my fpp , just so i can play sequences

What long files would you need?

**Comment by whitesoup12** [comment]
What version FPP and plugin do you have? If you have a remote-falcon.log file in you Logs tab that would be helpful, as well as your show name.

**Comment by smartaleciam** [comment]
FPP version 4.3.1 but also happened with 4.2.0 as well
Show name is "smartalecslights"
[remote-falcon.log](https://github.com/whitesoup12/remote-falcon-tracker/files/5501672/remote-falcon.log)

**Comment by whitesoup12** [comment]
@smartaleciam, looks like you're still running the 5.0.2 version of the plugin. You need to update it.

**Comment by smartaleciam** [comment]
i also have updated it to 5.1.0, an it still causing issues.
Why does it take over an kill my current show? (or what ever i have playing?)
i thought this remote falcon could be used with my show, not one or the other.
Thanks anyway

**Comment by whitesoup12** [comment]
You might try uninstalling and reinstalling the plugin. The issue you’re seeing used to be a problem but was fixed, so you shouldn’t still be seeing it.

**Comment by smartaleciam** [comment]
thats strange , cause thats how i discovered the issue, believe me i spent days trying to figure out what was causing it, eg different fpp versions an everything, even did a freash install of all config settings.. thats when i relised what was causing the issue, an when back to my orginal usb config (that got updated 3 times in its process from your original working firmware, an then this error started up), i can try on a freash install of everything, just to check remotefalcon again.

**Comment by whitesoup12** [comment]
@smartaleciam, any updates on this? Can this issue be closed or are you still having problems?

**Comment by smartaleciam** [comment]
Still having the same issue..
Look Im honestly over it,
Doing a Graceful Stopping of any Sequence or Media just after its started playing a play-list is unacceptable im sorry,
So It's disabled an will remain that way, till there is a fix.
Thanks for your Help.
P.s. I was Excited using it, till them updates broke it.

**Comment by whitesoup12** [comment]
If you've uninstalled and reinstalled the plugin and still having issues, I'd recommend asking the [RF group](https://www.facebook.com/groups/remotefalcon) on Facebook. It very likely could be a configuration issue.
